[package]
name = "crust-restorer"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[lib]
name = "crust_restorer"
crate-type = ["staticlib"]

[dependencies]
crust-syscall = { path = "../crust-syscall", default-features = false }
